/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Chalee
 */
public class Food extends javax.swing.JFrame {

 int score = 0;
    int count = 0;
    String stage="Started";
    String[][] foods = new String[][] {
       {"fried egg","ไข่ลวก","ไข่เจียว","ไข่ต้ม","ไข่ดาว"},
{"fried rice","ข้าวต้ม","ข้าวผัด","ขนมปัง","เนื้อบด"},
{"curry","แกงเขียวหวาน","แกงกะหรี่","กุ้งมังกร","อาหารสําเร็จรูป"},
{" chicken ","เนื้อไก่","เนื้อสัตว์","น่องไก่","ไก่อบ"},
{" bacon","ไข่ลวก","น้ำซุปข้น","ไก่ทอด","เบคอน"},
{"fried chicken","ไข่ลวก","น้ำซุปข้น","ไก่ทอด","เบคอน"},
{"omelette","ไข่ลวก","ไข่เจียว","ไข่ต้ม","ไข่ดาว"},
{"boiled egg","ไข่ลวก","ไข่เจียว","ไข่ต้ม","ไข่ดาว"},
{"ground beef","ข้าวต้ม","ข้าวผัด","ขนมปัง","เนื้อบด"},
{"delicatessen","แกงเขียวหวาน","แกงกะหรี่","กุ้งมังกร","อาหารสําเร็จรูป"}
};
    int [] ans = new int[]{4,2,2,1,4,3,2,3,4,4};
    public Food() {
        initComponents();
        this.nextCount();
    }
 private void nextCount(){
        if(count<10){
            wordCount1.setText("No.");
        option3.setVisible(true);
        option4.setVisible(true);
        wordGame.setText(foods[count][0]);
        wordCount.setText(Integer.toString(count+1));
        scoreNumber.setText(Integer.toString(score));
        option1.setText(foods[count][1]);
        option2.setText(foods[count][2]);
        option3.setText(foods[count][3]);
        option4.setText(foods[count][4]);
        }else{
            stage="Ended";
          scoreNumber.setText(Integer.toString(score));
         option1.setText("back");
         option2.setText("restart");
         option3.setVisible(false);
        option4.setVisible(false);
        if(score<=3){
         wordGame.setText("To bad, try again");
        }else if(score<=6){
         wordGame.setText("it's quite good");
        }else if(score<=9){
         wordGame.setText("Woww, NICE");
        }else{
         wordGame.setText("Perfect!!");
        }
        wordCount.setText("");
         wordCount1.setText("");
        
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        wordGame = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        option1 = new javax.swing.JButton();
        option3 = new javax.swing.JButton();
        option2 = new javax.swing.JButton();
        option4 = new javax.swing.JButton();
        wordCount1 = new javax.swing.JLabel();
        wordCount = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        scoreNumber = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wordGame.setBackground(new java.awt.Color(0, 0, 0));
        wordGame.setFont(new java.awt.Font("Ashcan BB", 1, 36)); // NOI18N
        wordGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wordGame.setText("Bread");
        bg.add(wordGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 130, 390, -1));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        back.setFont(new java.awt.Font("Ashcan BB", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("<<");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        close.setFont(new java.awt.Font("Ashcan BB", 1, 30)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("___________________________");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 360, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(204, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(204, 102, 0));
        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("___________________________");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 350, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        option1.setFont(new java.awt.Font("TH Sarabun New", 0, 11)); // NOI18N
        option1.setText("ทดสอบ");
        option1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1ActionPerformed(evt);
            }
        });
        jPanel1.add(option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 150, 60));

        option3.setFont(new java.awt.Font("TH Sarabun New", 0, 11)); // NOI18N
        option3.setText("jButton2");
        option3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3ActionPerformed(evt);
            }
        });
        jPanel1.add(option3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, 60));

        option2.setFont(new java.awt.Font("TH Sarabun New", 0, 11)); // NOI18N
        option2.setText("jButton2");
        option2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2ActionPerformed(evt);
            }
        });
        jPanel1.add(option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 150, 60));

        option4.setFont(new java.awt.Font("TH Sarabun New", 0, 11)); // NOI18N
        option4.setText("jButton2");
        option4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option4ActionPerformed(evt);
            }
        });
        jPanel1.add(option4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 150, 60));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 400, 230));

        wordCount1.setBackground(new java.awt.Color(0, 0, 0));
        wordCount1.setFont(new java.awt.Font("Ashcan BB", 1, 36)); // NOI18N
        wordCount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wordCount1.setText("No.");
        bg.add(wordCount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 70, -1));

        wordCount.setBackground(new java.awt.Color(0, 0, 0));
        wordCount.setFont(new java.awt.Font("Ashcan BB", 1, 36)); // NOI18N
        wordCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wordCount.setText("-");
        bg.add(wordCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 70, -1));

        scoreLabel.setBackground(new java.awt.Color(0, 0, 0));
        scoreLabel.setFont(new java.awt.Font("Ashcan BB", 1, 36)); // NOI18N
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setText("score:");
        bg.add(scoreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 150, 30));

        scoreNumber.setBackground(new java.awt.Color(0, 0, 0));
        scoreNumber.setFont(new java.awt.Font("Ashcan BB", 1, 36)); // NOI18N
        scoreNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreNumber.setText("-");
        bg.add(scoreNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void option1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1ActionPerformed
        int check = 1;
       if(stage=="Started"){
         if(check==ans[count]){
         score+=1;
         }
         count+=1;
         this.nextCount();
       }else{
       Page2 p = new Page2();
        p.setVisible(true);
        this.setVisible(false);
       }
    }//GEN-LAST:event_option1ActionPerformed

    private void option2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2ActionPerformed
         int check = 2;
       if(stage=="Started"){
         if(check==ans[count]){
         score+=1;
         }
         count+=1;
         this.nextCount();
       }else{
       score = 0;
     count = 0;
     stage="Started";
     this.nextCount();
       }
    
    }//GEN-LAST:event_option2ActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        Page2 p = new Page2();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void option3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3ActionPerformed
        int check = 3;
         if(check==ans[count]){
         score+=1;
         }
         count+=1;
         this.nextCount();
    
    }//GEN-LAST:event_option3ActionPerformed

    private void option4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4ActionPerformed
         int check = 4;
         if(check==ans[count]){
         score+=1;
         }
         count+=1;
         this.nextCount();
    
    }//GEN-LAST:event_option4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Food().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton option1;
    private javax.swing.JButton option2;
    private javax.swing.JButton option3;
    private javax.swing.JButton option4;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreNumber;
    private javax.swing.JLabel wordCount;
    private javax.swing.JLabel wordCount1;
    private javax.swing.JLabel wordGame;
    // End of variables declaration//GEN-END:variables
}
