/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Chalee
 */
public class Page2 extends javax.swing.JFrame {

    /**
     * Creates new form Page2
     */
    public Page2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        EXIT2 = new javax.swing.JPanel();
        EXIT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        กากบาท = new javax.swing.JLabel();
        กากบาท1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        WordGame3 = new javax.swing.JLabel();
        EXIT3 = new javax.swing.JPanel();
        EXIT1 = new javax.swing.JLabel();
        EXIT8 = new javax.swing.JPanel();
        EXIT9 = new javax.swing.JLabel();
        EXIT16 = new javax.swing.JPanel();
        EXIT17 = new javax.swing.JLabel();
        EXIT14 = new javax.swing.JPanel();
        EXIT15 = new javax.swing.JLabel();
        EXIT12 = new javax.swing.JPanel();
        EXIT13 = new javax.swing.JLabel();
        EXIT10 = new javax.swing.JPanel();
        EXIT7 = new javax.swing.JLabel();
        EXIT6 = new javax.swing.JPanel();
        EXIT11 = new javax.swing.JLabel();
        WordGame4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(0, 153, 153));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EXIT2.setBackground(new java.awt.Color(255, 255, 255));
        EXIT2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT2MouseClicked(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        EXIT.setText("Animals");
        EXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXITMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EXIT2Layout = new javax.swing.GroupLayout(EXIT2);
        EXIT2.setLayout(EXIT2Layout);
        EXIT2Layout.setHorizontalGroup(
            EXIT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EXIT2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(EXIT)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        EXIT2Layout.setVerticalGroup(
            EXIT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EXIT2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(EXIT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 150, 60));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("___________________________");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 370, -1));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        กากบาท.setFont(new java.awt.Font("Ashcan BB", 1, 30)); // NOI18N
        กากบาท.setForeground(new java.awt.Color(255, 255, 255));
        กากบาท.setText("X");
        กากบาท.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                กากบาทMouseClicked(evt);
            }
        });

        กากบาท1.setFont(new java.awt.Font("Ashcan BB", 1, 24)); // NOI18N
        กากบาท1.setForeground(new java.awt.Color(255, 255, 255));
        กากบาท1.setText("<<");
        กากบาท1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                กากบาท1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(กากบาท1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(กากบาท, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(กากบาท1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(กากบาท, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, 20));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("___________________________");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 360, -1));

        WordGame3.setFont(new java.awt.Font("Ashcan BB", 1, 50)); // NOI18N
        WordGame3.setForeground(new java.awt.Color(255, 255, 255));
        WordGame3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WordGame3.setText(" Category");
        bg.add(WordGame3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        EXIT3.setBackground(new java.awt.Color(255, 255, 255));
        EXIT3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT3MouseClicked(evt);
            }
        });

        EXIT1.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        EXIT1.setText("Places");
        EXIT1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EXIT3Layout = new javax.swing.GroupLayout(EXIT3);
        EXIT3.setLayout(EXIT3Layout);
        EXIT3Layout.setHorizontalGroup(
            EXIT3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EXIT3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(EXIT1)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        EXIT3Layout.setVerticalGroup(
            EXIT3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EXIT3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EXIT1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(EXIT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 60));

        EXIT8.setBackground(new java.awt.Color(255, 255, 255));
        EXIT8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT8MouseClicked(evt);
            }
        });

        EXIT9.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        EXIT9.setText("Home");
        EXIT9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EXIT8Layout = new javax.swing.GroupLayout(EXIT8);
        EXIT8.setLayout(EXIT8Layout);
        EXIT8Layout.setHorizontalGroup(
            EXIT8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EXIT8Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(EXIT9)
                .addGap(43, 43, 43))
        );
        EXIT8Layout.setVerticalGroup(
            EXIT8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EXIT8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EXIT9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(EXIT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 150, 60));

        EXIT16.setBackground(new java.awt.Color(255, 255, 255));
        EXIT16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT16MouseClicked(evt);
            }
        });

        EXIT17.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        EXIT17.setText("Body");
        EXIT17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EXIT16Layout = new javax.swing.GroupLayout(EXIT16);
        EXIT16.setLayout(EXIT16Layout);
        EXIT16Layout.setHorizontalGroup(
            EXIT16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EXIT16Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(EXIT17)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        EXIT16Layout.setVerticalGroup(
            EXIT16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EXIT16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EXIT17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(EXIT16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 150, 60));

        EXIT14.setBackground(new java.awt.Color(255, 255, 255));
        EXIT14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT14MouseClicked(evt);
            }
        });

        EXIT15.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        EXIT15.setText("Food");
        EXIT15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EXIT14Layout = new javax.swing.GroupLayout(EXIT14);
        EXIT14.setLayout(EXIT14Layout);
        EXIT14Layout.setHorizontalGroup(
            EXIT14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EXIT14Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(EXIT15)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        EXIT14Layout.setVerticalGroup(
            EXIT14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EXIT14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EXIT15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(EXIT14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, 60));

        EXIT12.setBackground(new java.awt.Color(255, 255, 255));
        EXIT12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT12MouseClicked(evt);
            }
        });

        EXIT13.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        EXIT13.setText("Fruit");
        EXIT13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EXIT12Layout = new javax.swing.GroupLayout(EXIT12);
        EXIT12.setLayout(EXIT12Layout);
        EXIT12Layout.setHorizontalGroup(
            EXIT12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EXIT12Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(EXIT13)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        EXIT12Layout.setVerticalGroup(
            EXIT12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EXIT12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EXIT13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(EXIT12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 150, 60));

        EXIT10.setBackground(new java.awt.Color(255, 255, 255));
        EXIT10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT10MouseClicked(evt);
            }
        });

        EXIT7.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        EXIT7.setText("Vegetable");
        EXIT7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EXIT10Layout = new javax.swing.GroupLayout(EXIT10);
        EXIT10.setLayout(EXIT10Layout);
        EXIT10Layout.setHorizontalGroup(
            EXIT10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EXIT10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(EXIT7)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        EXIT10Layout.setVerticalGroup(
            EXIT10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EXIT10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EXIT7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(EXIT10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 150, 60));

        EXIT6.setBackground(new java.awt.Color(255, 255, 255));
        EXIT6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT6MouseClicked(evt);
            }
        });

        EXIT11.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        EXIT11.setText("Verb");
        EXIT11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EXIT6Layout = new javax.swing.GroupLayout(EXIT6);
        EXIT6.setLayout(EXIT6Layout);
        EXIT6Layout.setHorizontalGroup(
            EXIT6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EXIT6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(EXIT11)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        EXIT6Layout.setVerticalGroup(
            EXIT6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EXIT6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EXIT11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(EXIT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 150, 60));

        WordGame4.setFont(new java.awt.Font("Ashcan BB", 1, 50)); // NOI18N
        WordGame4.setForeground(new java.awt.Color(0, 102, 102));
        WordGame4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WordGame4.setText(" Category");
        bg.add(WordGame4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITMouseClicked
        // TODO add your handling code here:
        Animals a = new Animals();
        a.setVisible(true);
   
    }//GEN-LAST:event_EXITMouseClicked

    private void EXIT2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT2MouseClicked
        // TODO add your handling code here:
        Animals a = new Animals();
        a.setVisible(true);
        
    }//GEN-LAST:event_EXIT2MouseClicked

    private void กากบาทMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_กากบาทMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_กากบาทMouseClicked

    private void EXIT1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT1MouseClicked
        // TODO add your handling code here:
        Places p = new Places();
        p.setVisible(true);
    }//GEN-LAST:event_EXIT1MouseClicked

    private void EXIT3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT3MouseClicked
        // TODO add your handling code here:
        Places p = new Places();
        p.setVisible(true);
    }//GEN-LAST:event_EXIT3MouseClicked

    private void EXIT7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT7MouseClicked
        // TODO add your handling code here:
       Vegetable v = new Vegetable();
       v.setVisible(true);
    }//GEN-LAST:event_EXIT7MouseClicked

    private void EXIT9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT9MouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_EXIT9MouseClicked

    private void EXIT8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT8MouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_EXIT8MouseClicked

    private void EXIT6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT6MouseClicked
        // TODO add your handling code here:
       Verb vb = new Verb();
       vb.setVisible(true);
    }//GEN-LAST:event_EXIT6MouseClicked

    private void EXIT11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT11MouseClicked
        // TODO add your handling code here:
       Verb vb = new Verb();
       vb.setVisible(true);
    }//GEN-LAST:event_EXIT11MouseClicked

    private void EXIT13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT13MouseClicked
        // TODO add your handling code here:
       Fruit f = new Fruit();
       f.setVisible(true);
    }//GEN-LAST:event_EXIT13MouseClicked

    private void EXIT15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT15MouseClicked
        // TODO add your handling code here:
       Food fo = new Food();
       fo.setVisible(true);
    }//GEN-LAST:event_EXIT15MouseClicked

    private void EXIT17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT17MouseClicked
        // TODO add your handling code here:
       Body b = new Body();
       b.setVisible(true);
    }//GEN-LAST:event_EXIT17MouseClicked

    private void EXIT16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT16MouseClicked
        // TODO add your handling code here:
        Body b = new Body();
       b.setVisible(true);
    }//GEN-LAST:event_EXIT16MouseClicked

    private void EXIT14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT14MouseClicked
        // TODO add your handling code here:
       Food fo = new Food();
       fo.setVisible(true);
    }//GEN-LAST:event_EXIT14MouseClicked

    private void EXIT12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT12MouseClicked
        // TODO add your handling code here:
       Fruit f = new Fruit();
       f.setVisible(true);
    }//GEN-LAST:event_EXIT12MouseClicked

    private void EXIT10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT10MouseClicked
        // TODO add your handling code here:
       Vegetable v = new Vegetable();
       v.setVisible(true);
    }//GEN-LAST:event_EXIT10MouseClicked

    private void กากบาท1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_กากบาท1MouseClicked
        // TODO add your handling code here:
        WordGame w = new WordGame();
        w.setVisible(true);
    }//GEN-LAST:event_กากบาท1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EXIT;
    private javax.swing.JLabel EXIT1;
    private javax.swing.JPanel EXIT10;
    private javax.swing.JLabel EXIT11;
    private javax.swing.JPanel EXIT12;
    private javax.swing.JLabel EXIT13;
    private javax.swing.JPanel EXIT14;
    private javax.swing.JLabel EXIT15;
    private javax.swing.JPanel EXIT16;
    private javax.swing.JLabel EXIT17;
    private javax.swing.JPanel EXIT2;
    private javax.swing.JPanel EXIT3;
    private javax.swing.JPanel EXIT6;
    private javax.swing.JLabel EXIT7;
    private javax.swing.JPanel EXIT8;
    private javax.swing.JLabel EXIT9;
    private javax.swing.JLabel WordGame3;
    private javax.swing.JLabel WordGame4;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel กากบาท;
    private javax.swing.JLabel กากบาท1;
    // End of variables declaration//GEN-END:variables
}
