/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Chalee
 */
public class Page2 extends javax.swing.JFrame {

    /**
     * Creates new form Page2
     */
    public Page2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        animal2 = new javax.swing.JPanel();
        animal1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        WordGame3 = new javax.swing.JLabel();
        places2 = new javax.swing.JPanel();
        places1 = new javax.swing.JLabel();
        hom2 = new javax.swing.JPanel();
        hom1 = new javax.swing.JLabel();
        body2 = new javax.swing.JPanel();
        body1 = new javax.swing.JLabel();
        food2 = new javax.swing.JPanel();
        food1 = new javax.swing.JLabel();
        fruit2 = new javax.swing.JPanel();
        fruit1 = new javax.swing.JLabel();
        vegetable2 = new javax.swing.JPanel();
        vegetable1 = new javax.swing.JLabel();
        verb2 = new javax.swing.JPanel();
        verb1 = new javax.swing.JLabel();
        WordGame4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(0, 153, 153));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        animal2.setBackground(new java.awt.Color(255, 255, 255));
        animal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                animal2MouseClicked(evt);
            }
        });

        animal1.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        animal1.setText("Animals");
        animal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                animal1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout animal2Layout = new javax.swing.GroupLayout(animal2);
        animal2.setLayout(animal2Layout);
        animal2Layout.setHorizontalGroup(
            animal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(animal2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(animal1)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        animal2Layout.setVerticalGroup(
            animal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(animal2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(animal1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(animal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 150, 60));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("___________________________");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 370, -1));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        close.setFont(new java.awt.Font("Ashcan BB", 1, 30)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        back.setFont(new java.awt.Font("Ashcan BB", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("<<");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, 20));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("___________________________");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 360, -1));

        WordGame3.setFont(new java.awt.Font("Ashcan BB", 1, 50)); // NOI18N
        WordGame3.setForeground(new java.awt.Color(255, 255, 255));
        WordGame3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WordGame3.setText(" Category");
        bg.add(WordGame3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        places2.setBackground(new java.awt.Color(255, 255, 255));
        places2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                places2MouseClicked(evt);
            }
        });

        places1.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        places1.setText("Places");
        places1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                places1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout places2Layout = new javax.swing.GroupLayout(places2);
        places2.setLayout(places2Layout);
        places2Layout.setHorizontalGroup(
            places2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(places2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(places1)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        places2Layout.setVerticalGroup(
            places2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(places2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(places1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(places2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 60));

        hom2.setBackground(new java.awt.Color(255, 255, 255));
        hom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hom2MouseClicked(evt);
            }
        });

        hom1.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        hom1.setText("Home");
        hom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hom1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hom2Layout = new javax.swing.GroupLayout(hom2);
        hom2.setLayout(hom2Layout);
        hom2Layout.setHorizontalGroup(
            hom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hom2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(hom1)
                .addGap(43, 43, 43))
        );
        hom2Layout.setVerticalGroup(
            hom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hom1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(hom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 150, 60));

        body2.setBackground(new java.awt.Color(255, 255, 255));
        body2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                body2MouseClicked(evt);
            }
        });

        body1.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        body1.setText("Body");
        body1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                body1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout body2Layout = new javax.swing.GroupLayout(body2);
        body2.setLayout(body2Layout);
        body2Layout.setHorizontalGroup(
            body2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(body1)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        body2Layout.setVerticalGroup(
            body2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(body1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(body2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 150, 60));

        food2.setBackground(new java.awt.Color(255, 255, 255));
        food2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                food2MouseClicked(evt);
            }
        });

        food1.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        food1.setText("Food");
        food1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                food1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout food2Layout = new javax.swing.GroupLayout(food2);
        food2.setLayout(food2Layout);
        food2Layout.setHorizontalGroup(
            food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(food2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(food1)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        food2Layout.setVerticalGroup(
            food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, food2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(food1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(food2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, 60));

        fruit2.setBackground(new java.awt.Color(255, 255, 255));
        fruit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fruit2MouseClicked(evt);
            }
        });

        fruit1.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        fruit1.setText("Fruit");
        fruit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fruit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fruit2Layout = new javax.swing.GroupLayout(fruit2);
        fruit2.setLayout(fruit2Layout);
        fruit2Layout.setHorizontalGroup(
            fruit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fruit2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(fruit1)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        fruit2Layout.setVerticalGroup(
            fruit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fruit2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fruit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(fruit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 150, 60));

        vegetable2.setBackground(new java.awt.Color(255, 255, 255));
        vegetable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vegetable2MouseClicked(evt);
            }
        });

        vegetable1.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        vegetable1.setText("Vegetable");
        vegetable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vegetable1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout vegetable2Layout = new javax.swing.GroupLayout(vegetable2);
        vegetable2.setLayout(vegetable2Layout);
        vegetable2Layout.setHorizontalGroup(
            vegetable2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vegetable2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(vegetable1)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        vegetable2Layout.setVerticalGroup(
            vegetable2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vegetable2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vegetable1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(vegetable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 150, 60));

        verb2.setBackground(new java.awt.Color(255, 255, 255));
        verb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verb2MouseClicked(evt);
            }
        });

        verb1.setFont(new java.awt.Font("Ashcan BB", 0, 24)); // NOI18N
        verb1.setText("Verb");
        verb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verb1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout verb2Layout = new javax.swing.GroupLayout(verb2);
        verb2.setLayout(verb2Layout);
        verb2Layout.setHorizontalGroup(
            verb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verb2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(verb1)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        verb2Layout.setVerticalGroup(
            verb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verb2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verb1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(verb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 150, 60));

        WordGame4.setFont(new java.awt.Font("Ashcan BB", 1, 50)); // NOI18N
        WordGame4.setForeground(new java.awt.Color(0, 102, 102));
        WordGame4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WordGame4.setText(" Category");
        bg.add(WordGame4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animal1MouseClicked
        // TODO add your handling code here:
        Animals a = new Animals();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_animal1MouseClicked

    private void animal2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animal2MouseClicked
        // TODO add your handling code here:
        Animals a = new Animals();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_animal2MouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void places1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_places1MouseClicked
        // TODO add your handling code here:
        Places p = new Places();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_places1MouseClicked

    private void places2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_places2MouseClicked
        // TODO add your handling code here:
        Places p = new Places();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_places2MouseClicked

    private void vegetable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vegetable1MouseClicked
        // TODO add your handling code here:
       Vegetable v = new Vegetable();
       v.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_vegetable1MouseClicked

    private void hom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hom1MouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hom1MouseClicked

    private void hom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hom2MouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hom2MouseClicked

    private void verb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verb2MouseClicked
        // TODO add your handling code here:
       Verb vb = new Verb();
       vb.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_verb2MouseClicked

    private void verb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verb1MouseClicked
        // TODO add your handling code here:
       Verb vb = new Verb();
       vb.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_verb1MouseClicked

    private void fruit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fruit1MouseClicked
        // TODO add your handling code here:
       Fruit f = new Fruit();
       f.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_fruit1MouseClicked

    private void food1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_food1MouseClicked
        // TODO add your handling code here:
       Food fo = new Food();
       fo.setVisible(true);
    }//GEN-LAST:event_food1MouseClicked

    private void body1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_body1MouseClicked
        // TODO add your handling code here:
       Body b = new Body();
       b.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_body1MouseClicked

    private void body2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_body2MouseClicked
        // TODO add your handling code here:
        Body b = new Body();
       b.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_body2MouseClicked

    private void food2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_food2MouseClicked
        // TODO add your handling code here:
       Food fo = new Food();
       fo.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_food2MouseClicked

    private void fruit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fruit2MouseClicked
        // TODO add your handling code here:
       Fruit f = new Fruit();
       f.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_fruit2MouseClicked

    private void vegetable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vegetable2MouseClicked
        // TODO add your handling code here:
       Vegetable v = new Vegetable();
       v.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_vegetable2MouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        WordGame w = new WordGame();
        w.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WordGame3;
    private javax.swing.JLabel WordGame4;
    private javax.swing.JLabel animal1;
    private javax.swing.JPanel animal2;
    private javax.swing.JLabel back;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel body1;
    private javax.swing.JPanel body2;
    private javax.swing.JLabel close;
    private javax.swing.JLabel food1;
    private javax.swing.JPanel food2;
    private javax.swing.JLabel fruit1;
    private javax.swing.JPanel fruit2;
    private javax.swing.JLabel hom1;
    private javax.swing.JPanel hom2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel places1;
    private javax.swing.JPanel places2;
    private javax.swing.JLabel vegetable1;
    private javax.swing.JPanel vegetable2;
    private javax.swing.JLabel verb1;
    private javax.swing.JPanel verb2;
    // End of variables declaration//GEN-END:variables
}
